#!/usr/bin/env python3
"""Regenerate feed.xml (+ api/feeds.json) from content/index.json or api/catalog.json.

Run after publishing knowledge entries:
  python3 scripts/build_feeds.py
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://chengguruchun.github.io"
REPO = "chengguruchun/chengguruchun.github.io"
WATCH_URL = f"https://github.com/{REPO}/subscription"
COMMITS_ATOM = f"https://github.com/{REPO}/commits/main.atom"
RELEASES_ATOM = f"https://github.com/{REPO}/releases.atom"


def load_items() -> list[dict]:
    catalog = ROOT / "api" / "catalog.json"
    index = ROOT / "content" / "index.json"
    raw = None
    if catalog.exists():
        data = json.loads(catalog.read_text(encoding="utf-8"))
        raw = data.get("items") if isinstance(data, dict) else data
    if not raw and index.exists():
        data = json.loads(index.read_text(encoding="utf-8"))
        raw = data.get("items", [])
    if not raw:
        raise SystemExit("No catalog/index items found")
    return list(raw)


def parse_date(value: str | None) -> datetime | None:
    if not value or not isinstance(value, str):
        return None
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})", value.strip())
    if not m:
        return None
    y, mo, d = map(int, m.groups())
    return datetime(y, mo, d, tzinfo=timezone.utc)


def rfc822(dt: datetime | None) -> str:
    if dt is None:
        dt = datetime.now(timezone.utc)
    return format_datetime(dt)


def abs_url(path: str) -> str:
    if path.startswith("http://") or path.startswith("https://"):
        return path
    if not path.startswith("/"):
        path = "/" + path
    return BASE + path


def build_rss(items: list[dict]) -> str:
    # Prefer dated knowledge posts; skip vague ranges like 2024–2026 for channel ordering
    dated = []
    for it in items:
        dt = parse_date(it.get("date"))
        if dt is None:
            continue
        dated.append((dt, it))
    dated.sort(key=lambda x: x[0], reverse=True)

    channel_updated = dated[0][0] if dated else datetime.now(timezone.utc)
    blocks = []
    for dt, it in dated:
        title = escape(str(it.get("title") or it.get("id") or "untitled"))
        link = abs_url(str(it.get("url") or f"/"))
        desc = escape(str(it.get("excerpt") or ""))
        kind = escape(str(it.get("type") or "Entry"))
        guid = escape(link)
        blocks.append(
            f"""    <item>
      <title>{title}</title>
      <link>{link}</link>
      <guid isPermaLink=\"true\">{guid}</guid>
      <pubDate>{rfc822(dt)}</pubDate>
      <category>{kind}</category>
      <description>{desc}</description>
    </item>"""
        )

    return f"""<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">
  <channel>
    <title>AI Knowledge Lab</title>
    <link>{BASE}/</link>
    <description>chengguruchun · 面向 AI Agent 的个人知识博客（文章 / Diverse Lab 等有日期条目）</description>
    <language>zh-cn</language>
    <lastBuildDate>{rfc822(channel_updated)}</lastBuildDate>
    <atom:link href=\"{BASE}/feed.xml\" rel=\"self\" type=\"application/rss+xml\"/>
{chr(10).join(blocks)}
  </channel>
</rss>
"""


def build_feeds_index() -> dict:
    return {
        "updated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "content_rss": {
            "path": "/feed.xml",
            "url": f"{BASE}/feed.xml",
            "description": "Knowledge Lab content feed (regenerated by scripts/build_feeds.py on publish)"
        },
        "repo_watch": {
            "url": WATCH_URL,
            "description": "GitHub Watch settings for the site repository (real subscription)"
        },
        "repo_commits_atom": {
            "url": COMMITS_ATOM,
            "description": "Atom feed of main-branch commits — machine-readable repo watch without clicking Watch"
        },
        "repo_releases_atom": {
            "url": RELEASES_ATOM,
            "description": "Atom feed of GitHub Releases (if any)"
        }
    }


def main() -> None:
    items = load_items()
    rss = build_rss(items)
    (ROOT / "feed.xml").write_text(rss, encoding="utf-8")
    feeds = build_feeds_index()
    (ROOT / "api" / "feeds.json").write_text(
        json.dumps(feeds, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"wrote feed.xml ({rss.count('<item>')} items) and api/feeds.json")


if __name__ == "__main__":
    main()
