#!/usr/bin/env python3
"""Inject search-engine and social metadata into every page, then emit sitemap.xml / robots.txt.

Pages stay hand-authored; this script owns only the block between the seo markers,
so it can be re-run at any time and in CI with --check.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "api" / "catalog.json"

BEGIN = "  <!-- seo:begin (generated by scripts/build_seo.py — do not edit by hand) -->"
END = "  <!-- seo:end -->"

SITE_NAME = "AI Knowledge Lab"
AUTHOR = "chengguruchun"
LOCALE = "zh_CN"
LANG = "zh-CN"
OG_IMAGE = "/assets/img/og-cover.png"
TWITTER_CARD = "summary_large_image"

# Directories that never belong in a sitemap.
SKIP_DIRS = {".git", ".preview", ".local", ".pi", "node_modules", "__pycache__"}

# Pages that are section landings rather than a single piece of writing.
COLLECTIONS = {
    "/articles/": "Articles",
    "/diverse/": "Diverse Lab",
    "/projects/": "Projects",
    "/videos/": "Videos",
    "/tags/": "Tags / Search",
}

# `<title>` carries a section suffix for humans; headlines and share cards should not.
TITLE_SUFFIXES = (
    " · Articles",
    " · Diverse Lab",
    " · AI Knowledge Lab",
    " · Hot Words",
)

failures: list[str] = []


def fail(msg: str) -> None:
    failures.append(msg)
    print(f"FAIL {msg}")


def site_path(rel: str) -> str:
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("index.html")]
    return "/" + rel


def depth_prefix(rel: str) -> str:
    """Relative prefix back to site root, e.g. 'articles/foo.html' -> '../'."""
    return "../" * rel.count("/")


def load_catalog() -> tuple[str, dict[str, dict]]:
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    base = data.get("base_url", "").rstrip("/")
    by_url = {item["url"]: item for item in data.get("items", [])}
    return base, by_url


def html_files() -> list[Path]:
    out = []
    for p in sorted(ROOT.rglob("*.html")):
        if any(part in SKIP_DIRS for part in p.relative_to(ROOT).parts):
            continue
        out.append(p)
    return out


def extract(pattern: str, text: str) -> str | None:
    m = re.search(pattern, text, re.DOTALL | re.IGNORECASE)
    return m.group(1).strip() if m else None


def git_date(path: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", str(path)],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    stamp = out.stdout.strip()
    return stamp or None


def esc(value: str) -> str:
    return html.escape(value, quote=True)


def clean_title(page_title: str, item: dict | None) -> str:
    if item and item.get("title"):
        return item["title"]
    for suffix in TITLE_SUFFIXES:
        if page_title.endswith(suffix):
            return page_title[: -len(suffix)]
    return page_title


def meta(prop: str, content: str, *, name: bool = False) -> str:
    key = "name" if name else "property"
    return f'  <meta {key}="{prop}" content="{esc(content)}">'


def build_jsonld(path_url: str, title: str, desc: str, base: str, item: dict | None) -> dict:
    page_url = base + path_url

    if path_url == "/":
        return {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": SITE_NAME,
            "alternateName": "Blog for Agents",
            "url": base + "/",
            "description": desc,
            "inLanguage": LANG,
            "author": {
                "@type": "Person",
                "name": AUTHOR,
                "url": f"https://github.com/{AUTHOR}",
            },
        }

    if path_url == "/about/":
        return {
            "@context": "https://schema.org",
            "@type": "ProfilePage",
            "name": title,
            "url": page_url,
            "inLanguage": LANG,
            "mainEntity": {
                "@type": "Person",
                "name": AUTHOR,
                "description": desc,
                "url": f"https://github.com/{AUTHOR}",
                "knowsAbout": [
                    "AI Agents",
                    "Agent Infrastructure",
                    "Distributed Systems",
                    "Industrial IoT",
                ],
            },
        }

    if path_url in COLLECTIONS:
        return {
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "name": title,
            "headline": COLLECTIONS[path_url],
            "url": page_url,
            "description": desc,
            "inLanguage": LANG,
            "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": base + "/"},
        }

    section = "Articles" if path_url.startswith("/articles/") else "Diverse Lab"
    published = (item or {}).get("published_date") or (item or {}).get("date")
    node: dict = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": title,
        "description": desc,
        "url": page_url,
        "mainEntityOfPage": {"@type": "WebPage", "@id": page_url},
        "inLanguage": LANG,
        "articleSection": section,
        "author": {"@type": "Person", "name": AUTHOR, "url": f"https://github.com/{AUTHOR}"},
        "publisher": {"@type": "Organization", "name": SITE_NAME, "url": base + "/"},
        "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": base + "/"},
    }
    if published:
        node["datePublished"] = published
        node["dateModified"] = published
    if item and item.get("tags"):
        node["keywords"] = ", ".join(item["tags"])
    return node


def breadcrumbs(path_url: str, title: str, base: str) -> dict | None:
    if path_url.startswith("/articles/") and path_url != "/articles/":
        section, section_url = "Articles", "/articles/"
    elif path_url.startswith("/diverse/") and path_url != "/diverse/":
        section, section_url = "Diverse Lab", "/diverse/"
    else:
        return None
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": base + "/"},
            {"@type": "ListItem", "position": 2, "name": section, "item": base + section_url},
            {"@type": "ListItem", "position": 3, "name": title, "item": base + path_url},
        ],
    }


def render_block(rel: str, title: str, desc: str, base: str, item: dict | None) -> str:
    path_url = site_path(rel)
    page_url = base + path_url
    prefix = depth_prefix(rel)
    is_post = item is not None and path_url not in COLLECTIONS and path_url != "/"

    lines = [BEGIN]
    lines.append(f'  <link rel="canonical" href="{esc(page_url)}">')
    lines.append(
        f'  <link rel="alternate" type="application/rss+xml" '
        f'title="{esc(SITE_NAME)}" href="{prefix}feed.xml">'
    )
    lines.append(meta("og:type", "article" if is_post else "website"))
    lines.append(meta("og:site_name", SITE_NAME))
    lines.append(meta("og:locale", LOCALE))
    lines.append(meta("og:title", title))
    lines.append(meta("og:description", desc))
    lines.append(meta("og:url", page_url))
    lines.append(meta("og:image", base + OG_IMAGE))
    lines.append(meta("og:image:alt", SITE_NAME))

    if is_post:
        published = item.get("published_date") or item.get("date")
        if published:
            lines.append(meta("article:published_time", published))
        lines.append(meta("article:author", AUTHOR))
        for tag in item.get("tags", []):
            lines.append(meta("article:tag", tag))

    lines.append(meta("twitter:card", TWITTER_CARD, name=True))
    lines.append(meta("twitter:title", title, name=True))
    lines.append(meta("twitter:description", desc, name=True))
    lines.append(meta("twitter:image", base + OG_IMAGE, name=True))
    lines.append(meta("author", AUTHOR, name=True))

    payload = [build_jsonld(path_url, title, desc, base, item)]
    crumbs = breadcrumbs(path_url, title, base)
    if crumbs:
        payload.append(crumbs)
    for node in payload:
        blob = json.dumps(node, ensure_ascii=False, indent=2)
        blob = "\n".join("  " + ln for ln in blob.splitlines())
        lines.append('  <script type="application/ld+json">')
        lines.append(blob)
        lines.append("  </script>")

    lines.append(END)
    return "\n".join(lines)


BLOCK_RE = re.compile(
    r"[ \t]*" + re.escape(BEGIN.strip()) + r".*?" + re.escape(END.strip()) + r"[ \t]*\n?",
    re.DOTALL,
)
# A hand-written RSS link would duplicate the one this script manages.
STRAY_RSS_RE = re.compile(
    r"[ \t]*<link[^>]+application/rss\+xml[^>]*>\n?", re.IGNORECASE
)


def apply_to_file(path: Path, base: str, by_url: dict[str, dict], check: bool) -> bool:
    rel = path.relative_to(ROOT).as_posix()
    original = path.read_text(encoding="utf-8")

    stripped = BLOCK_RE.sub("", original)
    stripped = STRAY_RSS_RE.sub("", stripped)

    title = extract(r"<title>(.*?)</title>", stripped)
    # Attribute values cannot contain a raw quote, so stop at the first one rather
    # than letting a lazy match backtrack across trailing attributes.
    desc = extract(r'<meta\s+name="description"\s+content="([^"]*)"', stripped)
    if not title:
        fail(f"{rel}: missing <title>")
        return False
    if not desc:
        fail(f"{rel}: missing meta description")
        return False

    item = by_url.get(site_path(rel))
    title = clean_title(html.unescape(title), item)
    desc = html.unescape(desc)

    block = render_block(rel, title, desc, base, item)
    if "</head>" not in stripped:
        fail(f"{rel}: no </head>")
        return False

    updated = stripped.replace("</head>", block + "\n</head>", 1)
    if updated == original:
        return False

    if check:
        fail(f"{rel}: seo block is stale — run `python3 scripts/build_seo.py`")
        return False

    path.write_text(updated, encoding="utf-8")
    print(f"seo   {rel}")
    return True


def build_sitemap(base: str, by_url: dict[str, dict], check: bool) -> bool:
    entries = []
    for path in html_files():
        rel = path.relative_to(ROOT).as_posix()
        url = site_path(rel)
        item = by_url.get(url)
        lastmod = (
            (item or {}).get("published_date")
            or (item or {}).get("date")
            or git_date(path)
            or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        )
        if url == "/":
            priority = "1.0"
        elif url in COLLECTIONS or url in ("/about/", "/bench/", "/times/", "/now/"):
            priority = "0.8"
        else:
            priority = "0.7"
        entries.append((base + url, lastmod, priority))

    lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    lines.append('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    for url, lastmod, priority in sorted(entries):
        lines.append("  <url>")
        lines.append(f"    <loc>{esc(url)}</loc>")
        lines.append(f"    <lastmod>{lastmod}</lastmod>")
        lines.append(f"    <priority>{priority}</priority>")
        lines.append("  </url>")
    lines.append("</urlset>")
    body = "\n".join(lines) + "\n"

    target = ROOT / "sitemap.xml"
    if target.exists() and target.read_text(encoding="utf-8") == body:
        return False
    if check:
        fail("sitemap.xml is stale — run `python3 scripts/build_seo.py`")
        return False
    target.write_text(body, encoding="utf-8")
    print(f"write sitemap.xml ({len(entries)} urls)")
    return True


# The lab is meant to be read by agents, so model crawlers are named explicitly
# rather than left to the default Allow.
AGENT_CRAWLERS = [
    "GPTBot",
    "OAI-SearchBot",
    "ChatGPT-User",
    "ClaudeBot",
    "Claude-User",
    "anthropic-ai",
    "PerplexityBot",
    "Google-Extended",
    "Applebot-Extended",
    "CCBot",
    "Bytespider",
    "Amazonbot",
    "cohere-ai",
    "DuckAssistBot",
]


def build_robots(base: str, check: bool) -> bool:
    lines = ["User-agent: *", "Allow: /", ""]
    for bot in AGENT_CRAWLERS:
        lines.append(f"User-agent: {bot}")
        lines.append("Allow: /")
        lines.append("")
    lines.append(f"Sitemap: {base}/sitemap.xml")
    lines.append(f"# Agent entry points: {base}/SKILL.md · {base}/api/discover.json · {base}/llms.txt")
    body = "\n".join(lines) + "\n"

    target = ROOT / "robots.txt"
    if target.exists() and target.read_text(encoding="utf-8") == body:
        return False
    if check:
        fail("robots.txt is stale — run `python3 scripts/build_seo.py`")
        return False
    target.write_text(body, encoding="utf-8")
    print("write robots.txt")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify generated output is current without writing (for CI)",
    )
    args = ap.parse_args()

    if not CATALOG.exists():
        print(f"FAIL missing {CATALOG.relative_to(ROOT)}")
        return 1

    base, by_url = load_catalog()
    if not base:
        print("FAIL catalog.json has no base_url")
        return 1

    changed = 0
    for path in html_files():
        if apply_to_file(path, base, by_url, args.check):
            changed += 1
    if build_sitemap(base, by_url, args.check):
        changed += 1
    if build_robots(base, args.check):
        changed += 1

    if failures:
        print(f"\n{len(failures)} problem(s)")
        return 1
    print(f"\nOK · {changed} file(s) {'stale' if args.check else 'updated'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
